name: drydays
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  audioplayers: ^6.4.0
  shared_preferences: ^2.5.3
  flutter_blue_plus: ^1.35.4
  permission_handler: ^12.0.0+1
  flutter_launcher_icons: ^0.14.3
  wakelock_plus: ^1.2.11
  android_intent_plus: ^5.3.0
  flutter_foreground_task: ^6.1.2
  flutter_background_service: ^5.1.0
  flutter_local_notifications: ^19.1.0
  android_alarm_manager_plus: ^4.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
flutter:

  uses-material-design: true

  assets:
    - assets/images/drydays.png
    - assets/images/product.png
    - assets/images/product2.png
    - assets/images/product3.png
    - assets/images/ensuresis.png
    - assets/images/blog.png
    - assets/images/trendyol_logo.png
    - assets/alarms/1.mp3
    - assets/alarms/2.mp3
    - assets/alarms/3.mp3
    - assets/alarms/4.mp3
    - assets/alarms/5.mp3
    - assets/alarms/6.mp3
    - assets/images/pp.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/pp.png"

