// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdrLnnLva3zbaPLe4wmGS6h0bAAz8b7i4',
    appId: '1:65049702064:web:114a4366aa18aae3fb9575',
    messagingSenderId: '65049702064',
    projectId: 'dry-days-75a8f',
    authDomain: 'dry-days-75a8f.firebaseapp.com',
    storageBucket: 'dry-days-75a8f.firebasestorage.app',
    measurementId: 'G-NGR3SBLY2C',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBGW-8n-icUC1aLjvt8tptea2o7peIZsM',
    appId: '1:65049702064:ios:8ebd24b2380f1cdafb9575',
    messagingSenderId: '65049702064',
    projectId: 'dry-days-75a8f',
    storageBucket: 'dry-days-75a8f.firebasestorage.app',
    iosBundleId: 'com.aasoft.drydays',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBGW-8n-icUC1aLjvt8tptea2o7peIZsM',
    appId: '1:65049702064:ios:8ebd24b2380f1cdafb9575',
    messagingSenderId: '65049702064',
    projectId: 'dry-days-75a8f',
    storageBucket: 'dry-days-75a8f.firebasestorage.app',
    iosBundleId: 'com.aasoft.drydays',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdrLnnLva3zbaPLe4wmGS6h0bAAz8b7i4',
    appId: '1:65049702064:web:8402c55dce3e667afb9575',
    messagingSenderId: '65049702064',
    projectId: 'dry-days-75a8f',
    authDomain: 'dry-days-75a8f.firebaseapp.com',
    storageBucket: 'dry-days-75a8f.firebasestorage.app',
    measurementId: 'G-1DPZ0PH0DL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6pTnsc-_Ew_UWqL4aO4OeNpwfEBvKy9Y',
    appId: '1:65049702064:android:c8750f11951e6982fb9575',
    messagingSenderId: '65049702064',
    projectId: 'dry-days-75a8f',
    storageBucket: 'dry-days-75a8f.firebasestorage.app',
  );

}